name: Push Image to AWS ECR

on:
  push:
    branches: [master]
jobs:
  deployment:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      # - name: Linux update and install aws
      #   run: |
      #     sudo apt update
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install --update
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1

      - name: Build docker image
        run: make aws_docker_build

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push docker image to ECR
        run: make aws_docker_push
