name: Push Image to AWS ECR

on:
  push:
    branches: [master]
jobs:
  deployment:
    name: Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login AWS docker
        run: make aws_docker_login

      - name: Build docker image
        run: make aws_docker_build

      - name: Push docker image to ECR
        run: make aws_docker_push
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      #     aws-region: ap-southeast-1

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1
